{"uuid": "6d5d29cc-14e3-4062-a692-66f90f0b2dae", "children": ["35423517-1ad2-4370-b6aa-4cf64fd22e12"], "befores": [{"name": "init_driver", "status": "passed", "start": 1711091437006, "stop": 1711091446674}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'testsfailed'\n", "trace": "  File \"C:\\Users\\sharath.ls\\OneDrive - Feuji Software Solutions Pvt Ltd\\Documents\\Python\\PytestSeleniumlogZip\\PytestSelenium\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\sharath.ls\\OneDrive - Feuji Software Solutions Pvt Ltd\\Documents\\Python\\PytestSeleniumlogZip\\PytestSelenium\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 911, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\sharath.ls\\OneDrive - Feuji Software Solutions Pvt Ltd\\Documents\\Python\\PytestSeleniumlogZip\\PytestSelenium\\Tests\\configtest.py\", line 29, in init_driver\n    if not request.node.testsfailed:  # Check if the test failed\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1711091447505, "stop": 1711091450176}], "start": 1711091437006, "stop": 1711091450176}