{"name": "test_invalid_signin[chrome]", "status": "broken", "statusDetails": {"message": "KeyError: 'expected_ursl'", "trace": "self = <Tests.UI_Test.test_login.TestLogin object at 0x000002CF01300770>\nsetup_pages = (<selenium.webdriver.chrome.webdriver.WebDriver (session=\"5afc1eb886e37f2e6e02d7ab8576e7a4\")>, <Pages.loginPage.LoginP...<Pages.cartPage.CartPage object at 0x000002CF01301640>, <Pages.checkoutPage.CheckoutPage object at 0x000002CF01301820>)\nlogin_data = {'INVALID PASSWORD': 'Admin@123', 'PASSWORD': 'secret_sauce', 'Zipcode': '987867', 'firstName': 'Harry', ...}\nassertion_data = {'cart_heading': 'Shipping', 'expected_text': 'Epic sadface: Username and password do not match any user in this service', 'expected_url': 'https://www.saucedemo.com/inventory.html', 'product_name': 'Sauce Labs Backpack', ...}\n\n    @pytest.mark.run(order=1)\n    @allure.severity(allure.severity_level.NORMAL)\n    def test_invalid_signin(self, setup_pages, login_data, assertion_data):\n        allure.attach('Starting test_invalid_signin', allure.attachment_type.TEXT);logging.info(\"Starting test_invalid_signin\")\n        driver, login_page, _, _ = setup_pages\n        login_page.click_login(login_data['userName'], login_data['INVALID PASSWORD'])\n>       assert driver.current_url != assertion_data['expected_ursl']\nE       KeyError: 'expected_ursl'\n\nTests\\UI_Test\\test_login.py:19: KeyError"}, "attachments": [{"name": 