{"uuid": "41a497aa-011c-474e-9085-d0f1c21cd798", "children": ["26b81484-e614-46fe-b140-6c5d7ca5da72"], "befores": [{"name": "init_driver", "status": "passed", "start": 1711091843591, "stop": 1711091853293}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'testsfailed'\n", "trace": "  File \"C:\\Users\\sharath.ls\\OneDrive - Feuji Software Solutions Pvt Ltd\\Documents\\Python\\PytestSeleniumlogZip\\PytestSelenium\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\sharath.ls\\OneDrive - Feuji Software Solutions Pvt Ltd\\Documents\\Python\\PytestSeleniumlogZip\\PytestSelenium\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 911, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\sharath.ls\\OneDrive - Feuji Software Solutions Pvt Ltd\\Documents\\Python\\PytestSeleniumlogZip\\PytestSelenium\\Tests\\configtest.py\", line 29, in init_driver\n    if not request.node.testsfailed:  # Check if the test failed\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1711091853982, "stop": 1711091856639}], "start": 1711091843591, "stop": 1711091856639}